#!/usr/bin/env python3
"""
Extract Chinese strings from JS/JSON files and generate translation patches.
Usage: python3 translate_js.py <file_path>
Outputs translated content to stdout.
"""
import re
import sys
import json

# Chinese character regex
CN_RE = re.compile(r'[\u4e00-\u9fff]+')

def translate_simple(text):
    """Simple translation map for common UI strings."""
    translations = {
        # UI labels
        '提示词小助手': 'Prompt Assistant',
        '提示词优化': 'Prompt Optimization',
        '翻译': 'Translation',
        '图像反推': 'Image Caption',
        '历史功能': 'History',
        '标签功能': 'Tags',
        '规则配置': 'Rule Configuration',
        'API配置': 'API Configuration',
        '设置': 'Settings',
        '保存': 'Save',
        '取消': 'Cancel',
        '确定': 'OK',
        '删除': 'Delete',
        '添加': 'Add',
        '编辑': 'Edit',
        '搜索': 'Search',
        '加载中': 'Loading',
        '加载失败': 'Load failed',
        '保存成功': 'Saved successfully',
        '保存失败': 'Save failed',
        '请选择': 'Please select',
        '请输入': 'Please enter',
        '确认删除': 'Confirm delete',
        '操作成功': 'Operation successful',
        '操作失败': 'Operation failed',
        # Feature names
        '扩写': 'Expand',
        '标签': 'Tag',
        '历史': 'History',
        '撤销': 'Undo',
        '重做': 'Redo',
        '缓存': 'Cache',
        '清除缓存': 'Clear Cache',
        '翻译服务': 'Translation Service',
        '优化服务': 'Optimization Service',
        '反推服务': 'Caption Service',
        '模型列表': 'Model List',
        # Status messages
        '请求中': 'Requesting',
        '请求成功': 'Request successful',
        '请求失败': 'Request failed',
        '网络错误': 'Network error',
        '超时': 'Timeout',
        '未知错误': 'Unknown error',
        '数据加载中': 'Data loading',
        '数据加载完成': 'Data loaded',
        # Comments
        '创建': 'Create',
        '初始化': 'Initialize',
        '获取': 'Get',
        '设置': 'Set',
        '更新': 'Update',
        '渲染': 'Render',
        '显示': 'Show',
        '隐藏': 'Hide',
        '点击': 'Click',
        '事件': 'Event',
        '监听器': 'Listener',
        '回调': 'Callback',
        '工具': 'Tool',
        '容器': 'Container',
        '面板': 'Panel',
        '窗口': 'Window',
        '对话框': 'Dialog',
        '菜单': 'Menu',
        '按钮': 'Button',
        '输入框': 'Input',
        '下拉框': 'Dropdown',
        '复选框': 'Checkbox',
        '标签页': 'Tab',
        '列表': 'List',
        '卡片': 'Card',
        '标题': 'Title',
        '描述': 'Description',
        '内容': 'Content',
        '名称': 'Name',
        '类型': 'Type',
        '值': 'Value',
        '默认': 'Default',
        '自定义': 'Custom',
        '高级': 'Advanced',
        '基本': 'Basic',
        '通用': 'General',
        '选项': 'Options',
        '配置': 'Config',
        '参数': 'Parameters',
        '结果': 'Result',
        '状态': 'Status',
        '信息': 'Info',
        '警告': 'Warning',
        '错误': 'Error',
        '成功': 'Success',
        '失败': 'Failed',
        '提示': 'Tip',
        '注意': 'Note',
        '说明': 'Description',
        '帮助': 'Help',
        '关于': 'About',
        '版本': 'Version',
        '作者': 'Author',
        '日期': 'Date',
        '时间': 'Time',
        '大小': 'Size',
        '数量': 'Count',
        '总数': 'Total',
        '当前': 'Current',
        '上一个': 'Previous',
        '下一个': 'Next',
        '第一个': 'First',
        '最后一个': 'Last',
        '全部': 'All',
        '部分': 'Partial',
        '无': 'None',
        '有': 'Has',
        '是': 'Yes',
        '否': 'No',
        '真': 'True',
        '假': 'False',
        '开': 'On',
        '关': 'Off',
        '启用': 'Enable',
        '禁用': 'Disable',
        '激活': 'Activate',
        '停用': 'Deactivate',
        '运行': 'Run',
        '停止': 'Stop',
        '暂停': 'Pause',
        '继续': 'Continue',
        '开始': 'Start',
        '结束': 'End',
        '完成': 'Complete',
        '进行中': 'In progress',
        '等待中': 'Waiting',
        '处理中': 'Processing',
        '已处理': 'Processed',
        '未处理': 'Unprocessed',
        '已选择': 'Selected',
        '未选择': 'Not selected',
        '已保存': 'Saved',
        '未保存': 'Not saved',
        '已加载': 'Loaded',
        '未加载': 'Not loaded',
        '已更新': 'Updated',
        '未更新': 'Not updated',
        '已删除': 'Deleted',
        '未删除': 'Not deleted',
        '已创建': 'Created',
        '未创建': 'Not created',
        '已修改': 'Modified',
        '未修改': 'Not modified',
        # Longer phrases
        '正在加载': 'Loading...',
        '加载完成': 'Loading complete',
        '加载失败': 'Loading failed',
        '保存设置': 'Save settings',
        '恢复默认': 'Restore defaults',
        '确认操作': 'Confirm action',
        '是否确认': 'Are you sure?',
        '请确认': 'Please confirm',
        '请稍候': 'Please wait',
        '请稍后重试': 'Please try again later',
        '请检查网络': 'Please check network',
        '请检查输入': 'Please check input',
        '请输入内容': 'Please enter content',
        '请输入名称': 'Please enter name',
        '请选择服务': 'Please select service',
        '请选择模型': 'Please select model',
        '请选择规则': 'Please select rule',
        '创建成功': 'Created successfully',
        '创建失败': 'Creation failed',
        '更新成功': 'Updated successfully',
        '更新失败': 'Update failed',
        '删除成功': 'Deleted successfully',
        '删除失败': 'Delete failed',
        # Common JS comment patterns
        '获取配置': 'Get config',
        '初始化配置': 'Init config',
        '保存配置': 'Save config',
        '加载配置': 'Load config',
        '渲染界面': 'Render UI',
        '更新界面': 'Update UI',
        '绑定事件': 'Bind events',
        '解绑事件': 'Unbind events',
        '创建元素': 'Create element',
        '移除元素': 'Remove element',
        '显示面板': 'Show panel',
        '隐藏面板': 'Hide panel',
        '切换面板': 'Toggle panel',
        '关闭对话框': 'Close dialog',
        '打开对话框': 'Open dialog',
        '显示提示': 'Show tip',
        '隐藏提示': 'Hide tip',
        '显示错误': 'Show error',
        '隐藏错误': 'Hide error',
        '显示警告': 'Show warning',
        '显示成功': 'Show success',
        '更新状态': 'Update status',
        '获取数据': 'Get data',
        '保存数据': 'Save data',
        '加载数据': 'Load data',
        '更新数据': 'Update data',
        '删除数据': 'Delete data',
        '清除数据': 'Clear data',
        '刷新数据': 'Refresh data',
        '重置数据': 'Reset data',
        '验证数据': 'Validate data',
        '格式化数据': 'Format data',
        '解析数据': 'Parse data',
        '转换数据': 'Convert data',
        '处理数据': 'Process data',
        '返回数据': 'Return data',
        '发送请求': 'Send request',
        '接收响应': 'Receive response',
        '处理响应': 'Process response',
        '处理错误': 'Handle error',
        '捕获错误': 'Catch error',
        '抛出错误': 'Throw error',
        '记录日志': 'Log',
        '打印日志': 'Print log',
        '清除日志': 'Clear log',
        '检查状态': 'Check status',
        '检查配置': 'Check config',
        '检查数据': 'Check data',
        '检查输入': 'Check input',
        '检查输出': 'Check output',
        '检查结果': 'Check result',
        '检查错误': 'Check error',
        '检查网络': 'Check network',
        '检查连接': 'Check connection',
        '检查权限': 'Check permission',
        '检查版本': 'Check version',
        '检查更新': 'Check for updates',
        '自动更新': 'Auto update',
        '手动更新': 'Manual update',
        '立即更新': 'Update now',
        '稍后更新': 'Update later',
        '取消更新': 'Cancel update',
        '更新完成': 'Update complete',
        '更新失败': 'Update failed',
        # ComfyUI specific
        '节点': 'Node',
        '工作流': 'Workflow',
        '图像': 'Image',
        '视频': 'Video',
        '音频': 'Audio',
        '文本': 'Text',
        '提示': 'Prompt',
        '种子': 'Seed',
        '步数': 'Steps',
        '采样器': 'Sampler',
        '调度器': 'Scheduler',
        '模型': 'Model',
        '检查点': 'Checkpoint',
        'LoRA': 'LoRA',
        'VAE': 'VAE',
        '控制网': 'ControlNet',
        '放大': 'Upscale',
        '缩小': 'Downscale',
        '裁剪': 'Crop',
        '旋转': 'Rotate',
        '翻转': 'Flip',
        '缩放': 'Scale',
        '调整': 'Adjust',
        '混合': 'Blend',
        '合并': 'Merge',
        '分割': 'Split',
        '连接': 'Connect',
        '断开': 'Disconnect',
        '输入': 'Input',
        '输出': 'Output',
        '执行': 'Execute',
        '运行': 'Run',
        '停止': 'Stop',
        '暂停': 'Pause',
        '继续': 'Continue',
        '重试': 'Retry',
        '跳过': 'Skip',
        '忽略': 'Ignore',
        '确认': 'Confirm',
        '取消': 'Cancel',
        '确定': 'OK',
        '应用': 'Apply',
        '重置': 'Reset',
        '恢复': 'Restore',
        '备份': 'Backup',
        '导入': 'Import',
        '导出': 'Export',
        '上传': 'Upload',
        '下载': 'Download',
        '分享': 'Share',
        '收藏': 'Favorite',
        '取消收藏': 'Unfavorite',
        '置顶': 'Pin',
        '取消置顶': 'Unpin',
        '排序': 'Sort',
        '过滤': 'Filter',
        '分组': 'Group',
        '分类': 'Category',
        '标签': 'Tag',
        '备注': 'Note',
        '描述': 'Description',
        '标题': 'Title',
        '名称': 'Name',
        '类型': 'Type',
        '大小': 'Size',
        '格式': 'Format',
        '质量': 'Quality',
        '分辨率': 'Resolution',
        '宽度': 'Width',
        '高度': 'Height',
        '比例': 'Ratio',
        '方向': 'Direction',
        '位置': 'Position',
        '对齐': 'Align',
        '间距': 'Spacing',
        '边距': 'Margin',
        '填充': 'Padding',
        '边框': 'Border',
        '圆角': 'Radius',
        '阴影': 'Shadow',
        '透明度': 'Opacity',
        '颜色': 'Color',
        '背景': 'Background',
        '前景': 'Foreground',
        '主题': 'Theme',
        '风格': 'Style',
        '字体': 'Font',
        '字号': 'Font size',
        '行高': 'Line height',
        '字间距': 'Letter spacing',
        '段落': 'Paragraph',
        '缩进': 'Indent',
        '对齐方式': 'Alignment',
        '左对齐': 'Left align',
        '右对齐': 'Right align',
        '居中对齐': 'Center align',
        '两端对齐': 'Justify',
        # More phrases
        '功能设置': 'Feature Settings',
        '界面设置': 'Interface Settings',
        '翻译设置': 'Translation Settings',
        '优化设置': 'Optimization Settings',
        '反推设置': 'Caption Settings',
        '缓存设置': 'Cache Settings',
        '日志设置': 'Log Settings',
        '显示设置': 'Display Settings',
        '布局设置': 'Layout Settings',
        '主题设置': 'Theme Settings',
        '语言设置': 'Language Settings',
        '服务设置': 'Service Settings',
        '模型设置': 'Model Settings',
        '规则设置': 'Rule Settings',
        '标签设置': 'Tag Settings',
        '历史设置': 'History Settings',
        '默认规则': 'Default Rule',
        '自定义规则': 'Custom Rule',
        '未知规则': 'Unknown Rule',
        '临时规则': 'Temporary Rule',
        '扩写规则': 'Expand Rule',
        '翻译规则': 'Translation Rule',
        '反推规则': 'Caption Rule',
        '优化规则': 'Optimization Rule',
        '视频反推': 'Video Caption',
        '图像反推': 'Image Caption',
        '提示词翻译': 'Prompt Translation',
        '提示词扩写': 'Prompt Expansion',
        '节点文档翻译': 'Node Doc Translation',
        '自动检测': 'Auto Detect',
        '手动选择': 'Manual Select',
        '智能匹配': 'Smart Match',
        '精确匹配': 'Exact Match',
        '模糊匹配': 'Fuzzy Match',
        '部分匹配': 'Partial Match',
        '完全匹配': 'Full Match',
        '不匹配': 'No Match',
        '匹配成功': 'Match successful',
        '匹配失败': 'Match failed',
        '翻译完成': 'Translation complete',
        '翻译失败': 'Translation failed',
        '优化完成': 'Optimization complete',
        '优化失败': 'Optimization failed',
        '反推完成': 'Caption complete',
        '反推失败': 'Caption failed',
        '请求超时': 'Request timeout',
        '请求取消': 'Request cancelled',
        '请求中断': 'Request interrupted',
        '服务不可用': 'Service unavailable',
        '服务异常': 'Service error',
        '服务正常': 'Service OK',
        '模型不可用': 'Model unavailable',
        '模型加载失败': 'Model load failed',
        '模型加载成功': 'Model loaded',
        '配置无效': 'Invalid config',
        '配置有效': 'Valid config',
        '数据无效': 'Invalid data',
        '数据有效': 'Valid data',
        '输入无效': 'Invalid input',
        '输入有效': 'Valid input',
        '输出无效': 'Invalid output',
        '输出有效': 'Valid output',
        '参数无效': 'Invalid parameter',
        '参数有效': 'Valid parameter',
        '参数错误': 'Parameter error',
        '参数正确': 'Parameter OK',
        '格式错误': 'Format error',
        '格式正确': 'Format OK',
        '类型错误': 'Type error',
        '类型正确': 'Type OK',
        '值错误': 'Value error',
        '值正确': 'Value OK',
        '范围错误': 'Range error',
        '范围正确': 'Range OK',
        '长度错误': 'Length error',
        '长度正确': 'Length OK',
        '数量错误': 'Count error',
        '数量正确': 'Count OK',
        '频率错误': 'Frequency error',
        '频率正确': 'Frequency OK',
        '速率错误': 'Rate error',
        '速率正确': 'Rate OK',
        '时间错误': 'Time error',
        '时间正确': 'Time OK',
        '日期错误': 'Date error',
        '日期正确': 'Date OK',
    }
    return translations.get(text, text)

def extract_chinese_strings(filepath):
    """Extract unique Chinese strings from a file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Find all Chinese strings (in quotes or standalone)
    # Match strings like "中文" or '中文' or just 中文 in comments
    patterns = [
        r'"([^"]*[\u4e00-\u9fff][^"]*)"',  # "中文..."
        r"'([^']*[\u4e00-\u9fff][^']*)'",  # '中文...'
        r'`([^`]*[\u4e00-\u9fff][^`]*)`',  # `中文...`
        r'//.*?([\u4e00-\u9fff].*?)(?:\n|$)',  # // 中文...
        r'/\*.*?([\u4e00-\u9fff].*?)\*/',  # /* 中文... */
    ]
    
    all_matches = set()
    for pattern in patterns:
        matches = re.findall(pattern, content)
        for m in matches:
            # Extract Chinese portions
            cn_parts = CN_RE.findall(m)
            for part in cn_parts:
                if len(part) >= 1:
                    all_matches.add(part)
    
    return sorted(all_matches, key=len, reverse=True)

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python3 translate_js.py <file_path>")
        sys.exit(1)
    
    filepath = sys.argv[1]
    strings = extract_chinese_strings(filepath)
    print(f"Found {len(strings)} unique Chinese strings in {filepath}")
    for s in strings:
        translated = translate_simple(s)
        print(f"  '{s}' -> '{translated}'")
